In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
out_path = str("processed_endomondoHR_proper_interpolate.npy")

data = np.load(out_path,allow_pickle=True)[0]

In [8]:
columns = ['userId','gender','sport','id','longitude','latitude','altitude','timestamp','time_elapsed',
           'heart_rate','derived_speed','distance','tar_heart_rate','tar_derived_speed','since_begin','since_last']

In [9]:
df = pd.DataFrame(data=data[0],columns=columns)

In [ ]:
len(df)

In [15]:
dfs = []

# Iterate through the numpy array
for data_point in data:
    df = pd.DataFrame(data=data_point, columns=columns)
    dfs.append(df)

In [16]:
# Concatenate all the individual DataFrames into one DataFrame
final_df = pd.concat(dfs, ignore_index=True)

In [17]:
print("done")

done

In [18]:
final_df.sample(15)

,userId,gender,sport,id,longitude,latitude,altitude,timestamp,time_elapsed,heart_rate,derived_speed,distance,tar_heart_rate,tar_derived_speed,since_begin,since_last
4416350,6946869,male,run,290890652,-4.476218,36.718720,-1.826042,1390877795,-0.100279,-0.487098,-2.600167,-2.673856,136.407809,11.269307,-14.805054,-0.01158
18144447,9904679,male,bike (transport),343601510,-96.726581,33.062704,0.178808,1400697558,-0.057038,-0.175673,1.761468,1.548567,137.878350,22.234072,-14.805054,-0.01158
782635,14066832,male,bike,563457042,98.388005,7.843465,-2.221418,1386143639,-0.017809,3.450268,6.224345,10.387940,155.000000,33.453351,-14.805054,-0.01158
7024784,5173214,male,bike,221981293,-5.670793,43.458139,2.302811,1374937025,0.004034,3.132421,-4.248267,-2.840285,153.499134,7.126128,-14.805054,-0.01158
13367994,1468536,male,bike,408135809,5.604967,59.379305,-1.337948,1410632323,0.008492,8.744648,1.796219,3.921283,180.000000,22.321434,-14.805054,-0.01158
24640735,5727574,male,cross-country skiing,271364569,10.696853,61.157311,10.200647,1385175983,-0.017809,-7.141043,0.206777,-2.157961,104.987958,18.325717,-14.805054,-0.01158
21517587,510054,male,bike,434528146,11.825498,55.446490,-1.789520,1415365098,-0.083785,1.929516,3.845953,1.819153,147.819028,27.474284,-14.805054,-0.01158
6985271,13310164,male,bike,320251120,100.419653,13.559225,-2.740082,1395423854,-0.090917,1.567365,4.663586,12.350468,146.108957,29.529741,-14.805054,-0.01158
14711927,3575734,male,run,290028414,-6.350948,38.914977,0.797455,1390676119,-0.021375,-4.115521,-4.767859,-3.403896,119.274438,5.819920,-14.805054,-0.01158
21137907,2474825,male,run,499441937,13.448083,50.508139,2.579152,1428540318,-0.030291,2.842227,-1.375355,0.498903,152.128838,14.348377,-14.805054,-0.01158
29156201,508935,male,mountain bike,289607686,-47.556296,-22.726309,5.625082,1390538256,-0.077544,-7.162928,4.786715,13.730773,104.884619,29.839278,-14.805054,-0.01158
17392205,10099521,female,run,323713784,25.252878,54.674582,-0.522585,1384992064,-0.120339,0.002705,-3.070371,-1.936945,138.720651,10.087256,-14.805054,-0.01158
12098049,3709276,male,run,635790439,12.464377,56.090291,-2.208211,1448216143,-0.011568,4.638296,-1.101415,1.358255,160.609854,15.037037,-14.805054,-0.01158
25775801,432096,female,run,292374725,6.884124,58.930610,7.127723,1390681961,-0.077544,-5.092029,-5.557092,-3.078284,114.663377,3.835860,-14.805054,-0.01158
991506,982359,male,bike,313392950,9.882471,57.033322,-2.135292,1395773908,-0.119893,1.918131,3.985274,-0.550476,147.765268,27.824526,-14.805054,-0.01158

In [19]:
final_df

,userId,gender,sport,id,longitude,latitude,altitude,timestamp,time_elapsed,heart_rate,derived_speed,distance,tar_heart_rate,tar_derived_speed,since_begin,since_last
0,10921915,male,bike,396826535,24.649770,60.173349,-1.804467,1408898746,-0.122568,-8.197369,-7.082944,-4.372304,100.000000,7.105427e-15,1.378479e+06,2158.846078
1,10921915,male,bike,396826535,24.650143,60.173240,-1.818636,1408898754,-0.122122,-5.369012,-2.088780,-1.797320,113.355469,1.255489e+01,1.378479e+06,2158.846078
2,10921915,male,bike,396826535,24.650911,60.172980,-1.820717,1408898765,-0.121676,-3.916386,-0.351569,-0.055967,120.214752,1.692208e+01,1.378479e+06,2158.846078
3,10921915,male,bike,396826535,24.650669,60.172478,-1.847772,1408898778,-0.121230,-4.150721,-0.680039,-0.051062,119.108221,1.609634e+01,1.378479e+06,2158.846078
4,10921915,male,bike,396826535,24.649145,60.171861,-1.851729,1408898794,-0.120784,-3.841288,-0.279256,4.282176,120.569362,1.710387e+01,1.378479e+06,2158.846078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30897595,69,male,bike,596955589,11.771525,55.244205,-2.234575,1320187545,0.008938,-9.265715,-5.270313,-3.923857,94.955283,4.556796e+00,-1.480505e+01,-0.011580
30897596,69,male,bike,596955589,11.771511,55.244205,-2.236174,1320187548,0.009383,-9.286278,-5.250881,-3.912920,94.858186,4.605646e+00,-1.480505e+01,-0.011580
30897597,69,male,bike,596955589,11.771461,55.244217,-2.237819,1320187552,0.009829,-9.259218,-5.318247,-3.938114,94.985964,4.436295e+00,-1.480505e+01,-0.011580
30897598,69,male,bike,596955589,11.771368,55.244228,-2.241828,1320187556,0.010275,-9.468020,-5.083516,-3.905412,94.000000,5.026387e+00,-1.480505e+01,-0.011580
30897599,69,male,bike,596955589,11.771301,55.244244,-2.244250,1320187559,0.010721,-10.112773,-5.222602,-3.974627,90.955484,4.676738e+00,-1.480505e+01,-0.011580

thirty million eight hundred ninety-seven thousand six hundred rows

In [2]:
print('working')

working

### Top 5 sports having the most users

In [ ]:
ranked_sport_users_df = final_df.groupby('sport')['userId'].nunique().reset_index(name='count')
ranked_sport_users_df = ranked_sport_users_df.sort_values(by='count', ascending=False)

In [ ]:
ranked_sport_users_df

In [ ]:
ranked_sport_users_df.plot(x='sport', y='count', kind='line', marker='o')
plt.title('Count of Users per Sport')
plt.xticks(np.arange(39),ranked_sport_users_df['sport'],rotation=90) 
plt.xlabel('Sport')
plt.ylabel('Count')
plt.show()

In [ ]:
# Top 5 workout types
highest_sport_users_df = ranked_sport_users_df[:5]

In [ ]:
highest_sport_users_df

In [ ]:
# Caculate the total users, we will this result to compute percentage later
total_sports_users = ranked_sport_users_df['count'].sum()

In [ ]:
total_sports_users

In [ ]:
# Merge ranked_sport_users_df with final_df on 'sport'
merged_df = final_df.merge(ranked_sport_users_df, on='sport', how='left')

In [ ]:
merged_df.sample(10)

In [ ]:
# Filter rows where count >= 50
filtered_df = merged_df[merged_df['count'] >= 50]

# Drop the 'count' column if you don't need it in the final result
filtered_df = filtered_df.drop(columns=['count'])

In [ ]:
filtered_df.info()

In [ ]:
filtered_df = filtered_df.drop(columns=['id','longitude','latitude','altitude','time_elapsed','heart_rate','derived_speed','since_begin','since_last'])

In [ ]:
filtered_df.info()

In [ ]:
import pandas as pd
from surprise import Dataset, Reader, SVD
from surprise.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [81]:
filtered_df.columns

Index(['userId', 'gender', 'sport', 'timestamp', 'distance', 'tar_heart_rate',
       'tar_derived_speed'],
      dtype='object')

In [ ]:
# reader = Reader(rating_scale=(filtered_df['tar_heart_rate'].min(), filtered_df['tar_heart_rate'].max()))
# data = Dataset.load_from_df(filtered_df[['userId', 'sport', 'tar_heart_rate']], reader)
# trainset, testset = train_test_split(data, test_size=0.2) #kernel dying

In [ ]:
# Use Singular Value Decomposition (SVD) for collaborative filtering
# model = SVD()
# model.fit(trainset)

In [ ]:
# Content-Based Filtering
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
df['sport'] = df['sport'].fillna('')  # Handle missing values
tfidf_matrix = tfidf_vectorizer.fit_transform(df['sport'])

# Compute the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

# Function to get content-based recommendations
def get_content_based_recommendations(activity_name):
    idx = df[df['id'] == activity_name].index[0]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]  # Top 10 similar activities
    activity_indices = [i[0] for i in sim_scores]
    return df['id'].iloc[activity_indices]

# Example: Get content-based recommendations for an activity
activity_id = 12345  # Replace with an actual activity ID
content_based_recommendations = get_content_based_recommendations(activity_id)
print("Content-Based Recommendations:", content_based_recommendations.tolist())

In [57]:
# final_df.to_csv('final_processed.csv') # THIS WILL HANG YOUR COMPUTER DO NOT DO THIS

In [29]:
## Model - lightfm

In [55]:
from lightfm import LightFM
from lightfm.data import Dataset
from lightfm.evaluation import precision_at_k
from scipy.sparse import coo_matrix

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
df_encoded = pd.get_dummies(filtered_df, columns=['gender', 'sport'],dtype=int)

In [58]:
df_encoded.head(10)

,userId,longitude,latitude,altitude,timestamp,time_elapsed,distance,tar_heart_rate,tar_derived_speed,gender_female,...,gender_unknown,sport_bike,sport_bike (transport),sport_core stability training,sport_cross-country skiing,sport_hiking,sport_indoor cycling,sport_mountain bike,sport_run,sport_walk
0,10921915,24.649770,60.173349,-1.804467,1408898746,-0.122568,-4.372304,100.000000,7.105427e-15,0,...,0,1,0,0,0,0,0,0,0,0
1,10921915,24.650143,60.173240,-1.818636,1408898754,-0.122122,-1.797320,113.355469,1.255489e+01,0,...,0,1,0,0,0,0,0,0,0,0
2,10921915,24.650911,60.172980,-1.820717,1408898765,-0.121676,-0.055967,120.214752,1.692208e+01,0,...,0,1,0,0,0,0,0,0,0,0
3,10921915,24.650669,60.172478,-1.847772,1408898778,-0.121230,-0.051062,119.108221,1.609634e+01,0,...,0,1,0,0,0,0,0,0,0,0
4,10921915,24.649145,60.171861,-1.851729,1408898794,-0.120784,4.282176,120.569362,1.710387e+01,0,...,0,1,0,0,0,0,0,0,0,0
5,10921915,24.648350,60.171545,-1.885302,1408898800,-0.120339,3.336863,118.734256,2.761155e+01,0,...,0,1,0,0,0,0,0,0,0,0
6,10921915,24.645312,60.171237,-1.938118,1408898823,-0.119893,0.129972,115.256770,3.773543e+01,0,...,0,1,0,0,0,0,0,0,0,0
7,10921915,24.644701,60.170534,-1.929778,1408898839,-0.119447,6.794670,120.585896,3.309883e+01,0,...,0,1,0,0,0,0,0,0,0,0
8,10921915,24.644416,60.169210,-1.912165,1408898862,-0.119001,9.601575,126.205367,2.450925e+01,0,...,0,1,0,0,0,0,0,0,0,0
9,10921915,24.641415,60.168469,-1.913691,1408898891,-0.118556,4.147450,127.780494,1.967822e+01,0,...,0,1,0,0,0,0,0,0,0,0

In [85]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30497400 entries, 0 to 30897599
Data columns (total 21 columns):
 #   Column                         Dtype
---  ------                         -----
 0   userId                         int64
 1   longitude                      float64
 2   latitude                       float64
 3   altitude                       float64
 4   timestamp                      int64
 5   time_elapsed                   float64
 6   distance                       float64
 7   tar_heart_rate                 float64
 8   tar_derived_speed              float64
 9   gender_female                  int64
 10  gender_male                    int64
 11  gender_unknown                 int64
 12  sport_bike                     int64
 13  sport_bike (transport)         int64
 14  sport_core stability training  int64
 15  sport_cross-country skiing     int64
 16  sport_hiking                   int64
 17  sport_indoor cycling           int64
 18  sport_mountain bike            int64
 19  sport_run                      int64
 20  sport_walk                     int64
dtypes: float64(7), int64(14)
memory usage: 5.0 GB

In [49]:
# df_encoded.drop(['id','heart_rate','derived_speed','since_begin','since_last'],axis=1,inplace=True)

In [60]:
train_data, test_data = train_test_split(df_encoded, test_size=0.2, random_state=42)

In [61]:
# Create a user-item interaction matrix
dataset_train = Dataset()
dataset_train.fit(users=train_data['userId'], items=train_data.columns)
(interactions_train, _) = dataset_train.build_interactions([(user, item, 1) for user, item in zip(train_data['userId'], train_data.columns)])

In [62]:
# Create item feature matrix
item_features_train = coo_matrix(train_data.drop(['userId'], axis=1).values)

In [63]:
print('working')

working

In [64]:
# Build the model with content-based features
model = LightFM(loss='warp', random_state=42)
model.fit(interactions_train, item_features=item_features_train, epochs=10, num_threads=2)

In [65]:
dataset_test = Dataset()
dataset_test.fit(users=test_data['userId'], items=test_data.columns)
(interactions_test, _) = dataset_test.build_interactions([(user, item, 1) for user, item in zip(test_data['userId'], test_data.columns)])

In [66]:
item_features_test = coo_matrix(test_data.drop(['userId'], axis=1).values)

In [67]:
test_precision = precision_at_k(model, interactions_test, k=5, item_features=item_features_test).mean()

In [82]:
test_precision

0.05714286

In [70]:
# Example: Get recommendations for a user from the test set
user_id_to_recommend = test_data['userId'].iloc[0]
user_index = dataset_test.mapping()[0][user_id_to_recommend]
# Convert the range object to a list
item_indices = list(range(len(test_data.columns)))

In [71]:
# Predict scores for items
scores = model.predict(user_index, item_indices, item_features=item_features_test)

In [72]:
# Get indices of top recommended activities
top_indices = scores.argsort()[::-1]

# Get the corresponding activity names
recommendations = test_data.columns[top_indices].tolist()

print(f"Recommendations for User {user_id_to_recommend} in the test set: {recommendations}")
print(f"Precision at K on the test set: {test_precision}")

Recommendations for User 139383 in the test set: ['tar_heart_rate', 'gender_unknown', 'latitude', 'longitude', 'gender_male', 'sport_bike (transport)', 'sport_walk', 'distance', 'sport_run', 'sport_cross-country skiing', 'sport_hiking', 'sport_indoor cycling', 'sport_bike', 'timestamp', 'sport_core stability training', 'sport_mountain bike', 'tar_derived_speed', 'altitude', 'time_elapsed', 'gender_female', 'userId']
Precision at K on the test set: 0.05714286118745804