In [3]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
out_path = str("processed_endomondoHR_proper_interpolate.npy")

data = np.load(out_path,allow_pickle=True)[0]

In [6]:
type(data)

numpy.ndarray

In [7]:
len(data)

102992

In [8]:
columns = ['userId','gender','sport','id','longitude','latitude','altitude','timestamp','time_elapsed',
           'heart_rate','derived_speed','distance','tar_heart_rate','tar_derived_speed','since_begin','since_last']

In [9]:
dfs = []

# Iterate through the numpy array
for data_point in data:
    df = pd.DataFrame(data=data_point, columns=columns)
    dfs.append(df)

In [10]:
# Concatenate all the individual DataFrames into one DataFrame
final_df = pd.concat(dfs, ignore_index=True)

In [11]:
print("done")

done

In [12]:
final_df.sample(15)

,userId,gender,sport,id,longitude,latitude,altitude,timestamp,time_elapsed,heart_rate,derived_speed,distance,tar_heart_rate,tar_derived_speed,since_begin,since_last
10882368,3616044,female,bike,408254179,9.153682,55.864984,-1.416181,1409874111,-0.047677,-8.223345,-6.389941,-3.706284,99.877342,1.742149,-14.805054,-0.01158
21070086,4253141,male,bike,213054865,13.617095,55.834801,-1.977209,1373235863,-0.039652,7.233703,9.706518,18.437381,172.865335,42.207228,-14.805054,-0.01158
16265318,6601602,male,run,235278076,121.428160,31.199459,-0.407760,1377317032,-0.025388,1.151554,-3.303930,-1.607685,144.145502,9.500109,-14.805054,-0.01158
799735,14066832,male,bike,608363608,98.389297,7.843231,-2.262913,1379700172,-0.017809,3.245198,5.664574,1.899047,154.031664,32.046138,-14.805054,-0.01158
27347726,3689976,male,run,419263976,16.913914,52.467363,-1.183339,1412546986,-0.110977,-3.756669,-3.404270,-0.904076,120.968932,9.247864,-14.805054,-0.01158
17620422,5979382,male,bike,361531470,9.744056,56.948073,-2.123325,1403130908,-0.023604,-4.980773,7.571188,6.547819,115.188727,36.839197,-14.805054,-0.01158
22668019,745030,male,run,436881599,9.926553,57.033025,-2.459713,1415847038,-0.114098,-4.326577,-2.316983,-2.426892,118.277832,11.981208,-14.805054,-0.01158
2354929,7231044,male,bike,563516979,5.767673,45.194603,0.411042,1437241923,-0.020484,-7.858444,-1.258193,1.003499,101.600401,14.642912,-14.805054,-0.01158
15022675,2909018,male,bike,599388976,-7.392054,52.220149,-2.307462,1441728576,-0.044556,2.080946,1.811862,13.432659,148.534077,22.360758,-14.805054,-0.01158
1092584,1655221,male,run,313824675,19.603466,50.359224,2.849381,1395846691,0.004034,-1.112690,-4.495949,-0.706389,133.453767,6.503479,-14.805054,-0.01158
6113495,14544270,male,run,604406123,21.228467,52.202667,-1.110668,1442691319,-0.080218,6.390724,-1.608293,-2.339435,168.884799,13.762791,-14.805054,-0.01158
23410589,1362730,male,bike,623377643,14.451262,53.465970,-1.826567,1445815062,-0.082893,-7.035747,-31.007464,-16.414080,105.485165,-60.144131,-14.805054,-0.01158
9386012,159106,male,mountain bike,429593927,10.653996,55.062322,-1.805382,1414348104,-0.028062,4.319177,-1.290811,2.785963,159.102982,14.560912,-14.805054,-0.01158
28537257,1706844,male,bike,273225316,-1.423304,53.653336,-1.231670,1385762871,-0.097158,-5.854136,0.498451,1.507522,111.064720,19.058960,-14.805054,-0.01158
7942622,8221442,male,run,444216857,5.722112,58.542217,-2.122082,1417579835,-0.068182,-1.290723,-3.262511,-2.571120,132.613098,9.604232,-14.805054,-0.01158

In [13]:
final_df

,userId,gender,sport,id,longitude,latitude,altitude,timestamp,time_elapsed,heart_rate,derived_speed,distance,tar_heart_rate,tar_derived_speed,since_begin,since_last
0,10921915,male,bike,396826535,24.649770,60.173349,-1.804467,1408898746,-0.122568,-8.197369,-7.082944,-4.372304,100.000000,7.105427e-15,1.378479e+06,2158.846078
1,10921915,male,bike,396826535,24.650143,60.173240,-1.818636,1408898754,-0.122122,-5.369012,-2.088780,-1.797320,113.355469,1.255489e+01,1.378479e+06,2158.846078
2,10921915,male,bike,396826535,24.650911,60.172980,-1.820717,1408898765,-0.121676,-3.916386,-0.351569,-0.055967,120.214752,1.692208e+01,1.378479e+06,2158.846078
3,10921915,male,bike,396826535,24.650669,60.172478,-1.847772,1408898778,-0.121230,-4.150721,-0.680039,-0.051062,119.108221,1.609634e+01,1.378479e+06,2158.846078
4,10921915,male,bike,396826535,24.649145,60.171861,-1.851729,1408898794,-0.120784,-3.841288,-0.279256,4.282176,120.569362,1.710387e+01,1.378479e+06,2158.846078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30897595,69,male,bike,596955589,11.771525,55.244205,-2.234575,1320187545,0.008938,-9.265715,-5.270313,-3.923857,94.955283,4.556796e+00,-1.480505e+01,-0.011580
30897596,69,male,bike,596955589,11.771511,55.244205,-2.236174,1320187548,0.009383,-9.286278,-5.250881,-3.912920,94.858186,4.605646e+00,-1.480505e+01,-0.011580
30897597,69,male,bike,596955589,11.771461,55.244217,-2.237819,1320187552,0.009829,-9.259218,-5.318247,-3.938114,94.985964,4.436295e+00,-1.480505e+01,-0.011580
30897598,69,male,bike,596955589,11.771368,55.244228,-2.241828,1320187556,0.010275,-9.468020,-5.083516,-3.905412,94.000000,5.026387e+00,-1.480505e+01,-0.011580
30897599,69,male,bike,596955589,11.771301,55.244244,-2.244250,1320187559,0.010721,-10.112773,-5.222602,-3.974627,90.955484,4.676738e+00,-1.480505e+01,-0.011580

thirty million eight hundred ninety-seven thousand six hundred rows

In [14]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30897600 entries, 0 to 30897599
Data columns (total 16 columns):
 #   Column             Dtype
---  ------             -----
 0   userId             int64
 1   gender             object
 2   sport              object
 3   id                 int64
 4   longitude          float64
 5   latitude           float64
 6   altitude           float64
 7   timestamp          int64
 8   time_elapsed       float64
 9   heart_rate         float64
 10  derived_speed      float64
 11  distance           float64
 12  tar_heart_rate     float64
 13  tar_derived_speed  float64
 14  since_begin        float64
 15  since_last         float64
dtypes: float64(11), int64(3), object(2)
memory usage: 3.7+ GB

In [15]:
final_df.describe()

,userId,id,longitude,latitude,altitude,timestamp,time_elapsed,heart_rate,derived_speed,distance,tar_heart_rate,tar_derived_speed,since_begin,since_last
count,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07,3.089760e+07
mean,4.581047e+06,3.645500e+08,1.165609e+01,4.277707e+01,-9.621740e-02,1.398707e+09,-5.592344e-02,-3.683366e-01,-3.843169e-01,4.250600e+00,1.369686e+02,1.683976e+01,-1.420581e+00,9.381144e-03
std,3.877977e+06,1.598918e+08,4.954340e+01,2.009642e+01,4.635084e+00,3.392614e+07,3.860546e-02,4.602324e+00,1.952560e+02,4.696540e+02,2.173212e+01,4.908565e+02,4.295374e+03,6.726980e+00
min,6.900000e+01,2.579360e+05,-1.600009e+02,-5.149342e+01,-5.050843e+02,1.170119e+09,-1.225675e-01,-1.878613e+01,-7.636031e+03,-4.727050e+03,5.000000e+01,-1.917850e+04,-1.480505e+01,-1.158027e-02
25%,1.520156e+06,2.599629e+08,-3.608460e-01,3.947421e+01,-2.163103e+00,1.378562e+09,-8.924548e-02,-3.117461e+00,-3.076244e+00,-2.346531e+00,1.239873e+02,1.007249e+01,-1.480505e+01,-1.158027e-02
50%,3.381703e+06,3.597589e+08,1.089222e+01,5.016756e+01,-1.544809e+00,1.401550e+09,-5.592344e-02,7.840944e-02,-1.469524e+00,-4.721074e-01,1.390781e+02,1.411164e+01,-1.480505e+01,-1.158027e-02
75%,7.038373e+06,4.859358e+08,1.983358e+01,5.561294e+01,1.674268e-01,1.425227e+09,-2.260139e-02,2.815756e+00,3.403575e+00,3.878029e+00,1.520038e+02,2.636218e+01,-1.480505e+01,-1.158027e-02
max,1.548142e+07,6.740080e+08,1.773666e+02,6.968066e+01,1.422245e+02,1.554627e+09,1.072066e-02,1.298015e+01,1.895148e+05,3.544274e+05,2.000000e+02,4.764413e+05,1.378479e+06,2.158846e+03

In [16]:
print('done')

done

### Top 5 sports having the most users

In [17]:
ranked_sport_users_df = final_df.groupby('sport')['userId'].nunique().reset_index(name='count')
ranked_sport_users_df = ranked_sport_users_df.sort_values(by='count', ascending=False)

In [18]:
ranked_sport_users_df

                      sport  count
25                      run    753
3                      bike    741
20            mountain bike    305
4          bike (transport)    134
16           indoor cycling    109
37                     walk     85
7   core stability training     63
14                   hiking     55
8      cross-country skiing     53
21             orienteering     37
11          fitness walking     31
27                    skate     19
17                 kayaking     16
5          circuit training     14
9           downhill skiing     13
22            roller skiing     13
38          weight training     13
30                   soccer      9
23                   rowing      7
29              snowshoeing      6
36        treadmill running      5
12                     golf      5
15         horseback riding      4
33                 swimming      3
35                   tennis      2
10               elliptical      2
6                  climbing      2
2                basketball      2
28             snowboarding      2
32            stair climing      1
34             table tennis      1
0                  aerobics      1
31                   squash      1
26                  sailing      1
24                    rugby      1
1                 badminton      1
18             kite surfing      1
13               gymnastics      1
19             martial arts      1

In [19]:
merged_df = final_df.merge(ranked_sport_users_df, on='sport', how='left')

In [20]:
# Filter rows where count >= 50
filtered_df = merged_df[merged_df['count'] >= 50]

# Drop the 'count' column if you don't need it in the final result
filtered_df = filtered_df.drop(columns=['count'])

In [21]:
# filtered_df.head(5)

In [22]:
# !pip install lightfm

## LSTM Model

In [23]:
le = LabelEncoder()
filtered_df['gender'] = le.fit_transform(filtered_df['gender'])
filtered_df['sport'] = le.fit_transform(filtered_df['sport'])

In [24]:
X = filtered_df[['userId','id' ,'gender', 'sport', 'longitude', 'latitude', 'altitude',
        'timestamp', 'time_elapsed', 'distance',
        'tar_derived_speed', 'since_begin', 'since_last']]
y = filtered_df['tar_heart_rate']

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
# Normalizing numerical features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
#Convert to PyTorch tensors
X_train_tensor = torch.Tensor(X_train)
y_train_tensor = torch.Tensor(y_train.values)

X_test_tensor = torch.Tensor(X_test)
y_test_tensor = torch.Tensor(y_test.values)

In [28]:
# Create DataLoader
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [29]:
batch_size = 64
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False) #want sequential hence shuffle=False
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [30]:
class LSTMModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size, dropout_prob=0.3):
        super(LSTMModel, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=dropout_prob)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        out, _ = self.lstm(x)
        out = self.fc(out[:, -1, :])
        return out

In [31]:
# Instantiate the model
input_size = X_train.shape[1]
hidden_size = 64
num_layers = 2
output_size = 1

In [32]:
model = LSTMModel(input_size, hidden_size, num_layers, output_size, dropout_prob=0.3)

In [33]:
# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [33]:
print('in progress')

in progress

In [37]:
# Training the model
num_epochs = 10

for epoch in range(num_epochs):
    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()
#         outputs = model(batch_X)
        outputs = model(batch_X.unsqueeze(1))
        loss = torch.sqrt(criterion(outputs.squeeze(), batch_y)) 
        loss.backward()
        optimizer.step()
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [1/10], Loss: 20.5057
Epoch [2/10], Loss: 18.5289
Epoch [3/10], Loss: 18.9941
Epoch [4/10], Loss: 18.1700
Epoch [5/10], Loss: 18.5523
Epoch [6/10], Loss: 18.8155
Epoch [7/10], Loss: 19.2377
Epoch [8/10], Loss: 19.7342
Epoch [9/10], Loss: 19.2547
Epoch [10/10], Loss: 18.3847

In [38]:
torch.save(model.state_dict(), 'lstm_model_weights_v1.pth')

In [39]:
print('training done')

training done

In [2]:
## loading from saved model weight

In [34]:
# model = LSTMModel(input_size, hidden_size, num_layers, output_size, dropout_prob=0.3)
model.load_state_dict(torch.load('lstm_model_weights_v1.pth'))

In [ ]:
# # Evaluation
model.eval()
with torch.no_grad():
    test_outputs = model(X_test_tensor.unsqueeze(1))
    test_loss = criterion(test_outputs.squeeze(), y_test_tensor)
    print(f'Test Loss: {test_loss.item():.4f}')

In [2]:
# X_test[0]

In [4]:
# Make predictions
model.eval()
new_sequence_data = X_test[0]
with torch.no_grad():
    new_sequence = torch.Tensor(new_sequence_data)  # Replace with your new sequence data
    prediction = model(new_sequence.unsqueeze(0))
    print(f'Predicted Target Heart Rate: {prediction.item():.2f}')